set_property(DIRECTORY APPEND PROPERTY
    CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_LIST_DIR}/m4a_driver_sources.txt")

file(STRINGS
    "${CMAKE_CURRENT_LIST_DIR}/m4a_driver_sources.txt"
    PORYAAAA_M4A_DRIVER_SOURCE_PATHS
)

set(PORYAAAA_M4A_DRIVER_SOURCES)
foreach(path IN LISTS PORYAAAA_M4A_DRIVER_SOURCE_PATHS)
    list(APPEND PORYAAAA_M4A_DRIVER_SOURCES "${CMAKE_CURRENT_LIST_DIR}/${path}")
endforeach()
