#ifndef VOICEGROUP_CORE_H
#define VOICEGROUP_CORE_H

#pragma once

/* Generated by cbindgen from voicegroup-core. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define VOICEGROUP_CORE_PROGRAM_BANK_SIZE 128

typedef enum VoicegroupCoreStatus {
  VOICEGROUP_CORE_STATUS_OK = 0,
  VOICEGROUP_CORE_STATUS_NULL_ARGUMENT = 1,
  VOICEGROUP_CORE_STATUS_INVALID_UTF8 = 2,
  VOICEGROUP_CORE_STATUS_LOAD_FAILED = 3,
} VoicegroupCoreStatus;

typedef enum VoicegroupCoreDiagnosticSeverity {
  VOICEGROUP_CORE_DIAGNOSTIC_SEVERITY_ERROR = 0,
  VOICEGROUP_CORE_DIAGNOSTIC_SEVERITY_WARNING = 1,
} VoicegroupCoreDiagnosticSeverity;

typedef enum VoicegroupCoreProgramKind {
  VOICEGROUP_CORE_PROGRAM_KIND_EMPTY = 0,
  VOICEGROUP_CORE_PROGRAM_KIND_DIRECT_SOUND = 1,
  VOICEGROUP_CORE_PROGRAM_KIND_PROGRAMMABLE_WAVE = 2,
  VOICEGROUP_CORE_PROGRAM_KIND_SQUARE1 = 3,
  VOICEGROUP_CORE_PROGRAM_KIND_SQUARE2 = 4,
  VOICEGROUP_CORE_PROGRAM_KIND_NOISE = 5,
  VOICEGROUP_CORE_PROGRAM_KIND_KEYSPLIT = 6,
  VOICEGROUP_CORE_PROGRAM_KIND_KEYSPLIT_ALL = 7,
  VOICEGROUP_CORE_PROGRAM_KIND_CRY = 8,
} VoicegroupCoreProgramKind;

typedef struct VoicegroupCoreBankResult VoicegroupCoreBankResult;

typedef struct VoicegroupCoreProjectIndex VoicegroupCoreProjectIndex;

typedef struct VoicegroupCoreSourcePosition {
  /**
   * One-based source line for diagnostics crossing the C ABI.
   */
  size_t line;
  /**
   * One-based source column for diagnostics crossing the C ABI.
   */
  size_t column;
} VoicegroupCoreSourcePosition;

typedef struct VoicegroupCoreSourceRange {
  /**
   * First source position covered by a diagnostic.
   */
  struct VoicegroupCoreSourcePosition start;
  /**
   * Position immediately after the diagnostic span.
   */
  struct VoicegroupCoreSourcePosition end;
} VoicegroupCoreSourceRange;

typedef struct VoicegroupCoreDirectSoundProgram {
  /**
   * Base MIDI key used to pitch the DirectSound sample.
   */
  uint8_t key;
  /**
   * C-compatible pan value copied from the voice macro.
   */
  uint8_t pan;
  /**
   * Envelope attack byte used by the poryaaaa engine.
   */
  uint8_t attack;
  /**
   * Envelope decay byte used by the poryaaaa engine.
   */
  uint8_t decay;
  /**
   * Envelope sustain byte used by the poryaaaa engine.
   */
  uint8_t sustain;
  /**
   * Envelope release byte used by the poryaaaa engine.
   */
  uint8_t release;
} VoicegroupCoreDirectSoundProgram;

typedef struct VoicegroupCoreProgrammableWaveProgram {
  /**
   * Base MIDI key used to pitch the programmable-wave sample.
   */
  uint8_t key;
  uint8_t pan;
  uint8_t attack;
  uint8_t decay;
  uint8_t sustain;
  uint8_t release;
} VoicegroupCoreProgrammableWaveProgram;

typedef struct VoicegroupCoreSquare1Program {
  /**
   * Base MIDI key used to pitch square channel 1.
   */
  uint8_t key;
  /**
   * C-compatible pan value copied from the voice macro.
   */
  uint8_t pan;
  /**
   * Sweep byte used by square channel 1.
   */
  uint8_t sweep;
  /**
   * Masked duty value used by square channel 1.
   */
  uint8_t duty;
  /**
   * Masked envelope attack value matching C loader materialization.
   */
  uint8_t attack;
  /**
   * Masked envelope decay value matching C loader materialization.
   */
  uint8_t decay;
  /**
   * Masked envelope sustain value matching C loader materialization.
   */
  uint8_t sustain;
  /**
   * Masked envelope release value matching C loader materialization.
   */
  uint8_t release;
} VoicegroupCoreSquare1Program;

typedef struct VoicegroupCoreSquare2Program {
  /**
   * Base MIDI key used to pitch square channel 2.
   */
  uint8_t key;
  /**
   * C-compatible pan value copied from the voice macro.
   */
  uint8_t pan;
  /**
   * Masked duty value used by square channel 2.
   */
  uint8_t duty;
  /**
   * Masked envelope attack value matching C loader materialization.
   */
  uint8_t attack;
  /**
   * Masked envelope decay value matching C loader materialization.
   */
  uint8_t decay;
  /**
   * Masked envelope sustain value matching C loader materialization.
   */
  uint8_t sustain;
  /**
   * Masked envelope release value matching C loader materialization.
   */
  uint8_t release;
} VoicegroupCoreSquare2Program;

typedef struct VoicegroupCoreNoiseProgram {
  /**
   * Base MIDI key retained for parity with the source macro.
   */
  uint8_t key;
  /**
   * C-compatible pan value copied from the voice macro.
   */
  uint8_t pan;
  /**
   * Masked noise period value used by the poryaaaa engine.
   */
  uint8_t period;
  /**
   * Masked envelope attack value matching C loader materialization.
   */
  uint8_t attack;
  /**
   * Masked envelope decay value matching C loader materialization.
   */
  uint8_t decay;
  /**
   * Masked envelope sustain value matching C loader materialization.
   */
  uint8_t sustain;
  /**
   * Masked envelope release value matching C loader materialization.
   */
  uint8_t release;
} VoicegroupCoreNoiseProgram;

typedef struct VoicegroupCoreKeysplitProgram {
  /**
   * Fully expanded 128-entry note-to-sub-voicegroup slot table.
   */
  uint8_t table[128];
} VoicegroupCoreKeysplitProgram;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Loads a project index and writes an opaque handle to `out_index`.
 *
 * # Safety
 * `project_root` must be a valid NUL-terminated UTF-8 string. `out_index` must
 * be writable.
 */
enum VoicegroupCoreStatus voicegroup_core_project_index_load(const char *project_root,
                                                             struct VoicegroupCoreProjectIndex **out_index);

/**
 * Frees a project index handle.
 *
 * # Safety
 * `index` must be null or a handle returned by this library that has not been freed.
 */
void voicegroup_core_project_index_free(struct VoicegroupCoreProjectIndex *index);

/**
 * Loads one program bank from an existing project index.
 *
 * # Safety
 * `index` must be a valid project index handle. `bank_name` must be a valid
 * NUL-terminated UTF-8 string. `out_result` must be writable.
 */
enum VoicegroupCoreStatus voicegroup_core_project_index_load_program_bank(const struct VoicegroupCoreProjectIndex *index,
                                                                          const char *bank_name,
                                                                          struct VoicegroupCoreBankResult **out_result);

/**
 * Frees a bank result handle.
 *
 * # Safety
 * `result` must be null or a handle returned by this library that has not been freed.
 */
void voicegroup_core_bank_result_free(struct VoicegroupCoreBankResult *result);

/**
 * Returns whether a bank result contains a loaded bank.
 *
 * # Safety
 * `result` must be null or a valid bank result handle.
 */
bool voicegroup_core_bank_result_has_bank(const struct VoicegroupCoreBankResult *result);

/**
 * Returns the number of diagnostics in a bank result.
 *
 * # Safety
 * `result` must be null or a valid bank result handle.
 */
size_t voicegroup_core_bank_result_diagnostic_count(const struct VoicegroupCoreBankResult *result);

/**
 * Copies one diagnostic code into a caller-provided buffer.
 *
 * # Safety
 * `result` must be a valid bank result handle. `buffer` may be null only when
 * `buffer_len` is zero; otherwise it must be writable for `buffer_len` bytes.
 */
size_t voicegroup_core_bank_result_diagnostic_code(const struct VoicegroupCoreBankResult *result,
                                                   size_t index,
                                                   char *buffer,
                                                   size_t buffer_len);

/**
 * Copies one diagnostic message into a caller-provided buffer.
 *
 * # Safety
 * `result` must be a valid bank result handle. `buffer` may be null only when
 * `buffer_len` is zero; otherwise it must be writable for `buffer_len` bytes.
 */
size_t voicegroup_core_bank_result_diagnostic_message(const struct VoicegroupCoreBankResult *result,
                                                      size_t index,
                                                      char *buffer,
                                                      size_t buffer_len);

/**
 * Returns one diagnostic severity.
 *
 * # Safety
 * `result` must be null or a valid bank result handle.
 */
enum VoicegroupCoreDiagnosticSeverity voicegroup_core_bank_result_diagnostic_severity(const struct VoicegroupCoreBankResult *result,
                                                                                      size_t index);

/**
 * Writes one diagnostic source range.
 *
 * # Safety
 * `result` must be a valid bank result handle. `out_range` must be writable.
 */
bool voicegroup_core_bank_result_diagnostic_range(const struct VoicegroupCoreBankResult *result,
                                                  size_t index,
                                                  struct VoicegroupCoreSourceRange *out_range);

/**
 * Returns the program kind for a bank slot.
 *
 * # Safety
 * `result` must be null or a valid bank result handle.
 */
enum VoicegroupCoreProgramKind voicegroup_core_bank_result_program_kind(const struct VoicegroupCoreBankResult *result,
                                                                        size_t slot);

/**
 * Returns the poryaaaa/GBA voice type code for a bank slot.
 *
 * # Safety
 * `result` must be null or a valid bank result handle.
 */
uint8_t voicegroup_core_bank_result_program_type_code(const struct VoicegroupCoreBankResult *result,
                                                      size_t slot);

/**
 * Copies a bank slot display name into a caller-provided buffer.
 *
 * # Safety
 * `result` must be a valid bank result handle. `buffer` may be null only when
 * `buffer_len` is zero; otherwise it must be writable for `buffer_len` bytes.
 */
size_t voicegroup_core_bank_result_program_display_name(const struct VoicegroupCoreBankResult *result,
                                                        size_t slot,
                                                        char *buffer,
                                                        size_t buffer_len);

/**
 * Copies the relative asset path for a sample-backed bank slot.
 *
 * # Safety
 * `result` must be a valid bank result handle. `buffer` may be null only when
 * `buffer_len` is zero; otherwise it must be writable for `buffer_len` bytes.
 */
size_t voicegroup_core_bank_result_program_relative_path(const struct VoicegroupCoreBankResult *result,
                                                         size_t slot,
                                                         char *buffer,
                                                         size_t buffer_len);

/**
 * Copies the sub-voicegroup symbol for keysplit slots.
 *
 * # Safety
 * `result` must be a valid bank result handle. `buffer` may be null only when
 * `buffer_len` is zero; otherwise it must be writable for `buffer_len` bytes.
 */
size_t voicegroup_core_bank_result_program_sub_voicegroup(const struct VoicegroupCoreBankResult *result,
                                                          size_t slot,
                                                          char *buffer,
                                                          size_t buffer_len);

/**
 * Copies the keysplit table symbol for keysplit slots.
 *
 * # Safety
 * `result` must be a valid bank result handle. `buffer` may be null only when
 * `buffer_len` is zero; otherwise it must be writable for `buffer_len` bytes.
 */
size_t voicegroup_core_bank_result_program_keysplit_table_symbol(const struct VoicegroupCoreBankResult *result,
                                                                 size_t slot,
                                                                 char *buffer,
                                                                 size_t buffer_len);

/**
 * Writes DirectSound numeric fields for a bank slot.
 *
 * # Safety
 * `result` must be a valid bank result handle. `out_program` must be writable.
 */
bool voicegroup_core_bank_result_program_direct_sound(const struct VoicegroupCoreBankResult *result,
                                                      size_t slot,
                                                      struct VoicegroupCoreDirectSoundProgram *out_program);

/**
 * Writes programmable-wave numeric fields for a bank slot.
 *
 * # Safety
 * `result` must be a valid bank result handle. `out_program` must be writable.
 */
bool voicegroup_core_bank_result_program_programmable_wave(const struct VoicegroupCoreBankResult *result,
                                                           size_t slot,
                                                           struct VoicegroupCoreProgrammableWaveProgram *out_program);

/**
 * Writes Square 1 numeric fields for a bank slot.
 *
 * # Safety
 * `result` must be a valid bank result handle. `out_program` must be writable.
 */
bool voicegroup_core_bank_result_program_square1(const struct VoicegroupCoreBankResult *result,
                                                 size_t slot,
                                                 struct VoicegroupCoreSquare1Program *out_program);

/**
 * Writes Square 2 numeric fields for a bank slot.
 *
 * # Safety
 * `result` must be a valid bank result handle. `out_program` must be writable.
 */
bool voicegroup_core_bank_result_program_square2(const struct VoicegroupCoreBankResult *result,
                                                 size_t slot,
                                                 struct VoicegroupCoreSquare2Program *out_program);

/**
 * Writes noise numeric fields for a bank slot.
 *
 * # Safety
 * `result` must be a valid bank result handle. `out_program` must be writable.
 */
bool voicegroup_core_bank_result_program_noise(const struct VoicegroupCoreBankResult *result,
                                               size_t slot,
                                               struct VoicegroupCoreNoiseProgram *out_program);

/**
 * Writes keysplit table bytes for a bank slot.
 *
 * # Safety
 * `result` must be a valid bank result handle. `out_program` must be writable.
 */
bool voicegroup_core_bank_result_program_keysplit(const struct VoicegroupCoreBankResult *result,
                                                  size_t slot,
                                                  struct VoicegroupCoreKeysplitProgram *out_program);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VOICEGROUP_CORE_H */
