#ifndef PORYAAAA_AUDIO_TRACE_FORMAT_H
#define PORYAAAA_AUDIO_TRACE_FORMAT_H

#include <stdint.h>

/* Wire-format constants shared by trace producers and consumers. This header
 * deliberately depends on neither the audio runtime nor the M4A driver. */
#define PORYAAAA_AUDIO_TRACE_MAGIC "PORYAAAA_AUDIO_TRACE"
#define PORYAAAA_AUDIO_TRACE_VERSION 1u
#define PORYAAAA_AUDIO_TRACE_VERSION_TEXT "1"
#define PORYAAAA_GBA_IO_BASE UINT32_C(0x04000000)
#define PORYAAAA_GBA_CLOCK_HZ UINT32_C(16777216)
#define PORYAAAA_GBA_CLOCK_HZ_TEXT "16777216"
#define PORYAAAA_AUDIO_TRACE_HEADER PORYAAAA_AUDIO_TRACE_MAGIC " " PORYAAAA_AUDIO_TRACE_VERSION_TEXT
#define PORYAAAA_AUDIO_TRACE_CLOCK_LINE "CLOCK " PORYAAAA_GBA_CLOCK_HZ_TEXT
#define PORYAAAA_AUDIO_TRACE_LINE_CAPACITY 512u
#define PORYAAAA_TRACE_ORDER_EXTENDED UINT32_C(0x80000000)
#define PORYAAAA_TRACE_ORDER_SEQUENCE_SHIFT 16u
#define PORYAAAA_TRACE_ORDER_DELAY_MASK UINT32_C(0x0000FFFF)

#endif
